pipeline {
    parameters {
        choice(
            name: 'terraformAction',
            choices: ['apply', 'destroy'],
            description: 'Choose your Terraform action to perform'
        )
    }
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_KEY = credentials('AWS_SECRET_KEY')
    }
    agent any
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'iac', url: 'https://github.com/ranjitasd1/terrafoorm-automation.git' 
            }
        }
        stage('Plan') {
            steps {
                sh '''
                cd terraform
                pwd
                terraform init
                terraform plan -out=tfplan
                terraform show -no-color tfplan > tfplan.txt
                '''
            }
        }
        stage('Approval') {
            steps {
                script {
                    def plan = readFile 'terraform/tfplan.txt'
                    input message: "Do you want to proceed?",
                          parameters: [
                              text(
                                  name: 'plan',
                                  description: 'Please review the code/plan',
                                  defaultValue: plan
                              )
                          ]
                }
            }
        }
        stage('Creation/Destroy Stage') {
            when {
                expression {
                    return params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                }
            }
            steps {
                script {
                    if (params.terraformAction == 'apply') {
                        sh '''
                        pwd
                        cd terraform
                        terraform apply -input=false tfplan
                        '''
                    } else if (params.terraformAction == 'destroy') {
                        sh '''
                        pwd
                        cd terraform
                        terraform destroy -auto-approve
                        '''
                    }
                }
            }
        }
    }
}

